// Code generated by gravity-development-toolkit. DO NOT EDIT.
package gravity

//go:generate go run ./developing/tools genversion

// Version ...
const Version = "ep05-0abaa7 (expirimental/prototyping)"
