// Code generated by gravity-development-toolkit. DO NOT EDIT.
package gravity

//go:generate go run ./developing/tools genversion

// Version ...
const Version = "ep02-b66e58 (expirimental/prototyping)"
